#!/usr/bin/env python3
"""Deploy API keys to all currently-up pods.

Reads keys/{openrouter,openai,anthropic,huggingface}_api_keys.csv. For each
live pod found via RunPod + Vast APIs, writes:

  - POD_ENV_FILE from config.env (default /root/.env): KEY="value" lines,
    the canonical copy on the pod
  - A `set -a; . <env file>; set +a` block in ~/.bashrc and ~/.zshrc
    (idempotent — guarded by markers, only written once)
  - /root/.ipython/profile_default/startup/00-load-env.py so every
    IPython / Jupyter kernel auto-loads the env file at boot

Pods that aren't currently online are silently skipped. Re-running rewrites
the .env atomically (no duplicates), so this is safe to invoke at any time
after pod creation.

Usage:
  python3 copy_api_keys.py                 # all currently-up pods
  python3 copy_api_keys.py --pod gpu-elm       # one pod only
  python3 copy_api_keys.py --pod gpu-elm --pod gpu-maple
"""
import argparse
import concurrent.futures
import csv
import os
import shlex
import subprocess
import sys

from mydotenv import load_env
load_env()

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KEYS_DIR = os.path.join(BASE_DIR, "keys")

SSH_KEY = os.path.expanduser(
    os.environ["SHARED_SSH_KEY_PATH"]
)
SSH_USER = os.environ.get("SSH_USER", "root")
MACHINE_PREFIX = os.environ.get("MACHINE_NAME_PREFIX", "gpu")

# Each entry: (env var name to write into .env, source CSV filename in keys/).
# The HF token is intentionally written under both common names — different
# libraries pick different ones (huggingface_hub uses HF_TOKEN, transformers
# / datasets often look at HUGGING_FACE_HUB_TOKEN).
KEY_SOURCES = [
    ("OPENROUTER_API_KEY",     "openrouter_api_keys.csv"),
    ("OPENAI_API_KEY",         "openai_api_keys.csv"),
    ("ANTHROPIC_API_KEY",      "anthropic_api_keys.csv"),
    ("HF_TOKEN",               "huggingface_api_keys.csv"),
    ("HUGGING_FACE_HUB_TOKEN", "huggingface_api_keys.csv"),
]

ENV_PATH = os.environ.get("POD_ENV_FILE") or "/root/.env"
RC_FILES = ["/root/.bashrc", "/root/.zshrc"]
RC_MARKER_START = "# >>> api keys (managed by copy_api_keys.py) >>>"
RC_MARKER_END   = "# <<< api keys <<<"
RC_BLOCK = (
    f"{RC_MARKER_START}\n"
    f"set -a; [ -f {ENV_PATH} ] && . {ENV_PATH}; set +a\n"
    f"{RC_MARKER_END}\n"
)

IPY_STARTUP_DIR = "/root/.ipython/profile_default/startup"
IPY_STARTUP_PATH = f"{IPY_STARTUP_DIR}/00-load-env.py"
# Dependency-free on purpose (no python-dotenv on the pod): parses the
# KEY="value" lines that env_quote() below writes.
IPY_STARTUP_CONTENT = f"""# Auto-generated by copy_api_keys.py. Loads the pod's API keys into
# os.environ on every IPython / Jupyter kernel start, so notebooks can use
# os.environ['OPENROUTER_API_KEY'] etc. with no setup.
import os as _os
try:
    with open({ENV_PATH!r}) as _f:
        for _line in _f:
            _k, _sep, _v = _line.strip().partition("=")
            if not _sep or _k.startswith("#"):
                continue
            if len(_v) >= 2 and _v[0] == _v[-1] == '"':
                _v = _v[1:-1].replace('\\\\$', '$').replace('\\\\"', '"').replace('\\\\\\\\', '\\\\')
            _os.environ.setdefault(_k, _v)
except FileNotFoundError:
    pass
except Exception as _e:
    print(f"[startup] could not load {ENV_PATH}: {{_e}}")
"""


def read_keys_csv(path):
    """Return {hostname: key} from a 2-col CSV. Skips header rows and rows for other prefixes."""
    out = {}
    if not os.path.exists(path):
        return out
    prefix = MACHINE_PREFIX + "-"
    with open(path, "r", newline="") as f:
        for row in csv.reader(f):
            if not row or len(row) < 2:
                continue
            host, key = row[0].strip(), row[1].strip()
            if not host.startswith(prefix) or not key:
                continue
            out[host] = key
    return out


def env_quote(value):
    """Quote a value for KEY="..." in a sourced shell file / dotenv."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'


def build_env_file(pod_name, key_tables):
    lines = []
    for env_var, fname in KEY_SOURCES:
        keys = key_tables.get(fname, {})
        if pod_name in keys:
            lines.append(f"{env_var}={env_quote(keys[pod_name])}")
    if not lines:
        return ""
    return "# Auto-generated by copy_api_keys.py. Do not edit by hand.\n" \
           + "\n".join(lines) + "\n"


def get_live_endpoints():
    """Return {pod_name: (ip, port)} for pods currently up on RunPod + Vast.

    Best-effort: a failure on one provider does not hide the other.
    """
    endpoints = {}

    api_key = os.getenv("RUNPOD_API_KEY")
    if api_key:
        try:
            import runpod_compat as runpod
            runpod.api_key = api_key
            for pod in runpod.get_pods() or []:
                runtime = pod.get("runtime") or {}
                ports = runtime.get("ports") or []
                public_tcp = [p for p in ports
                              if isinstance(p, dict)
                              and p.get("type") == "tcp"
                              and p.get("isIpPublic")]
                if not public_tcp:
                    continue
                ip = public_tcp[0].get("ip")
                port = public_tcp[0].get("publicPort")
                name = pod.get("name")
                if name and ip and port:
                    endpoints[name] = (ip, str(port))
        except Exception as e:
            sys.exit(f"RunPod lookup failed, so no keys were deployed: {e}")
    else:
        print("# Warning: RUNPOD_API_KEY not set; skipping RunPod pods",
              file=sys.stderr)

    try:
        from vast_provider import get_vast_pods
        for vp in get_vast_pods():
            name = vp.get("name")
            ip = vp.get("ip")
            port = vp.get("ssh_port")
            if name and ip and port:
                endpoints[name] = (str(ip), str(port))
    except Exception as e:
        print(f"# Warning: Vast lookup failed: {e}", file=sys.stderr)

    return endpoints


def ssh_run(ip, port, remote_cmd, stdin_data=None, timeout=60):
    cmd = [
        "ssh",
        "-i", SSH_KEY,
        "-p", str(port),
        "-o", "ConnectTimeout=15",
        "-o", "StrictHostKeyChecking=no",
        "-o", "UserKnownHostsFile=/dev/null",
        "-o", "BatchMode=yes",
        "-o", "LogLevel=ERROR",
        f"{SSH_USER}@{ip}",
        remote_cmd,
    ]
    return subprocess.run(
        cmd,
        input=stdin_data,
        capture_output=True,
        text=True,
        timeout=timeout,
        check=False,
    )


def deploy_to_pod(pod_name, ip, port, key_tables):
    env_content = build_env_file(pod_name, key_tables)
    if not env_content:
        return (pod_name, False, "no keys in any CSV for this pod")

    # 1. Write the canonical .env atomically.
    q = shlex.quote(ENV_PATH)
    tmp = shlex.quote(ENV_PATH + ".tmp")
    write_env = (
        f"mkdir -p $(dirname {q}) && "
        f"cat > {tmp} && "
        f"mv {tmp} {q} && "
        f"chmod 600 {q}"
    )
    r = ssh_run(ip, port, write_env, stdin_data=env_content)
    if r.returncode != 0:
        return (pod_name, False,
                f".env write failed: {r.stderr.strip() or r.stdout.strip()}")

    # 2. Append a source-the-env block to each rc file, guarded by marker
    #    so re-runs don't duplicate.
    rc_parts = []
    for rc in RC_FILES:
        rc_parts.append(
            f"touch {rc}; grep -qF {shlex.quote(RC_MARKER_START)} {rc} || "
            f"printf '\\n%s' {shlex.quote(RC_BLOCK)} >> {rc}"
        )
    r = ssh_run(ip, port, " && ".join(rc_parts))
    if r.returncode != 0:
        return (pod_name, False,
                f"rc install failed: {r.stderr.strip() or r.stdout.strip()}")

    # 3. IPython / Jupyter startup hook (auto-load .env on every kernel start).
    ipy_cmd = f"mkdir -p {IPY_STARTUP_DIR} && cat > {IPY_STARTUP_PATH}"
    r = ssh_run(ip, port, ipy_cmd, stdin_data=IPY_STARTUP_CONTENT)
    if r.returncode != 0:
        return (pod_name, False,
                f"ipython startup write failed: "
                f"{r.stderr.strip() or r.stdout.strip()}")

    return (pod_name, True, "ok")


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument(
        "--pod", action="append", default=[],
        help="Restrict to this pod name (e.g. gpu-elm). Can be repeated. "
             "Default: every currently-up pod.",
    )
    ap.add_argument(
        "--max-parallel", type=int,
        default=int(os.getenv("API_KEYS_MAX_PARALLEL", "30")),
        help="Max concurrent SSH workers (default 30).",
    )
    args = ap.parse_args()

    # Load CSVs once. Duplicate filenames (huggingface appears twice in
    # KEY_SOURCES) are de-duplicated naturally by the dict.
    key_tables = {}
    print("Loading CSVs from", KEYS_DIR)
    for _, fname in KEY_SOURCES:
        if fname in key_tables:
            continue
        path = os.path.join(KEYS_DIR, fname)
        keys = read_keys_csv(path)
        key_tables[fname] = keys
        status = f"{len(keys)} entries" if keys else "MISSING / empty"
        print(f"  {fname}: {status}")

    if not any(key_tables.values()):
        print("\nNo keys loaded from any CSV. Nothing to deploy.")
        return 1

    print("\nResolving live pod endpoints (RunPod + Vast)...")
    # Only this fleet's pods: never SSH into other pods on the account.
    endpoints = {n: e for n, e in get_live_endpoints().items()
                 if n.startswith(MACHINE_PREFIX + "-")}
    print(f"  {len(endpoints)} pod(s) online")

    if args.pod:
        from pod_names import to_full
        wanted = {to_full(p) for p in args.pod}
        filtered = {n: e for n, e in endpoints.items() if n in wanted}
        not_online = sorted(wanted - set(filtered.keys()))
        for missing in not_online:
            print(f"  ERROR: requested pod {missing!r} is not online (no SSH endpoint yet?)")
        endpoints = filtered
        if not_online:
            return 1

    if not endpoints:
        print("\nNo pods to deploy to. Exiting.")
        return 0

    print(f"\nDeploying to {len(endpoints)} pod(s) "
          f"with up to {args.max_parallel} workers...\n")
    results = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.max_parallel) as ex:
        futures = {
            ex.submit(deploy_to_pod, name, ip, port, key_tables): name
            for name, (ip, port) in endpoints.items()
        }
        for fut in concurrent.futures.as_completed(futures):
            try:
                results.append(fut.result())
            except Exception as e:
                results.append((futures[fut], False, f"crashed: {e}"))

    results.sort()
    ok = 0
    for name, success, msg in results:
        tag = "OK  " if success else "FAIL"
        print(f"  [{tag}] {name}: {msg}")
        if success:
            ok += 1

    print(f"\nDone: {ok}/{len(results)} pod(s) succeeded.")
    return 0 if ok == len(results) else 1


if __name__ == "__main__":
    sys.exit(main())
